"""12_geometry_descriptor_implementation.py

Experiment 12: Descriptor Implementation.

Implements the frozen geometry descriptor from Experiments 10--11 on the
thermal-anchor grid in processed_data/phase1_unified_master.csv.

Descriptor components:
- normalized cross-sectional shape represented by PCA scores
- local amplitude / relief
- signed elevation
- validity / finite-support metadata
- regime metadata

Track 21 remains sealed. This script only processes Tracks 8, 10, and 14.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from importlib.machinery import SourceFileLoader
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import json
import math
import sys
import warnings

import numpy as np
import pandas as pd


warnings.filterwarnings("ignore", category=RuntimeWarning)

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = REPO_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.append(str(SRC_DIR))

from nsf_fmrg_data import load_wyko_asc


EXP07_PATH = REPO_ROOT / "scripts" / "07_heightmap_2d_object_identity_audit.py"
EXP09_PATH = REPO_ROOT / "scripts" / "09_heightmap_cross_section_shape_coherence_audit.py"
exp07 = SourceFileLoader("exp07_heightmap_2d_object_identity_audit", str(EXP07_PATH)).load_module()
exp09 = SourceFileLoader("exp09_heightmap_cross_section_shape_coherence_audit", str(EXP09_PATH)).load_module()


SEALED_TRACKS = {21}
TRACK_IDS = [8, 10, 14]
assert not (set(TRACK_IDS) & SEALED_TRACKS), "Track 21 is sealed and must not be analyzed."

PHASE1_MASTER_PATH = REPO_ROOT / "processed_data" / "phase1_unified_master.csv"
HEIGHT_DIR = REPO_ROOT / "data" / "raw" / "height_maps"
EXP09_DIR = REPO_ROOT / "processed_data" / "run_outputs" / "09_heightmap_cross_section_shape_coherence_audit_20260714_223253" / "tables"
EXP11_DIR = REPO_ROOT / "processed_data" / "run_outputs" / "11_pca_representation_evaluation_20260714_230834" / "tables"

N_RETAINED_PCA_COMPONENTS = 5
CENTRAL_Y_MIN_MM = float(exp09.CENTRAL_Y_MIN_MM)
CENTRAL_Y_MAX_MM = float(exp09.CENTRAL_Y_MAX_MM)
BOUNDARY_EXCLUSION_MM = float(exp09.BOUNDARY_EXCLUSION_MM)
MIN_TOTAL_FINITE_FRACTION = float(exp09.MIN_TOTAL_FINITE_FRACTION)
MIN_CENTRAL_FINITE_FRACTION = float(exp09.MIN_CENTRAL_FINITE_FRACTION)
MIN_BASELINE_SUPPORT_COUNT = int(exp09.MIN_BASELINE_SUPPORT_COUNT)
MIN_NORMALIZATION_SUPPORT_FRACTION = float(exp09.MIN_NORMALIZATION_SUPPORT_FRACTION)


@dataclass
class TrackDescriptorCache:
    track_id: int
    x_mm: np.ndarray
    y_mm: np.ndarray
    fields: Dict[str, np.ndarray]
    x_min_mm: float
    x_max_mm: float


_PCA_MODEL: Optional[Dict[str, np.ndarray]] = None
_TRACK_CACHE: Dict[int, TrackDescriptorCache] = {}
_REGIME_TABLE: Optional[pd.DataFrame] = None
_FULL_EXP09_Y_GRID: Optional[np.ndarray] = None
_OUTPUT_DIR: Optional[Path] = None


def robust_mad(values: np.ndarray, scale: bool = True) -> float:
    return float(exp07.robust_mad(values, scale=scale))


def safe_percentile(values: np.ndarray, q: float) -> float:
    v = np.asarray(values, dtype=float)
    v = v[np.isfinite(v)]
    if v.size == 0:
        return float("nan")
    return float(np.nanpercentile(v, q))


def safe_iqr(values: np.ndarray) -> float:
    return safe_percentile(values, 75) - safe_percentile(values, 25)


def load_pca_model() -> Dict[str, np.ndarray]:
    """Load the frozen PCA shape model generated by Experiment 11."""

    global _PCA_MODEL, _FULL_EXP09_Y_GRID
    if _PCA_MODEL is not None:
        return _PCA_MODEL

    pca_npz = np.load(EXP11_DIR / "pca_model_arrays.npz")
    exp09_npz = np.load(EXP09_DIR / "normalized_profiles_by_track.npz")
    _FULL_EXP09_Y_GRID = np.asarray(exp09_npz["y_grid_mm"], dtype=float)

    y_retained = np.asarray(pca_npz["y_grid_mm"], dtype=float)
    y_full = np.asarray(_FULL_EXP09_Y_GRID, dtype=float)
    retained_indices: List[int] = []
    for y in y_retained:
        idx = int(np.nanargmin(np.abs(y_full - y)))
        if not math.isclose(float(y_full[idx]), float(y), rel_tol=0.0, abs_tol=1e-10):
            raise RuntimeError("Could not align Experiment 11 retained PCA y-grid to Experiment 09 full y-grid.")
        retained_indices.append(idx)

    components = np.asarray(pca_npz["components"], dtype=float)
    if components.shape[0] < N_RETAINED_PCA_COMPONENTS:
        raise RuntimeError("PCA model contains fewer components than requested.")

    _PCA_MODEL = {
        "y_full_grid_mm": y_full,
        "y_retained_grid_mm": y_retained,
        "retained_full_grid_indices": np.asarray(retained_indices, dtype=int),
        "mean_profile": np.asarray(pca_npz["mean_profile"], dtype=float),
        "components": components,
        "explained_variance_ratio": np.asarray(pca_npz["explained_variance_ratio"], dtype=float),
    }
    return _PCA_MODEL


def load_track_cache(track_id: int) -> TrackDescriptorCache:
    """Load and preprocess one development track using Experiment 07/09 conventions."""

    if track_id in SEALED_TRACKS:
        raise ValueError("Track 21 is sealed and must not be analyzed.")
    if track_id not in TRACK_IDS:
        raise ValueError(f"Unsupported track_id={track_id}; allowed tracks are {TRACK_IDS}.")
    if track_id in _TRACK_CACHE:
        return _TRACK_CACHE[track_id]

    hm = load_wyko_asc(HEIGHT_DIR, track_id, crop_to_common=True)
    x_mm = np.asarray(hm["x_actual_mm"], dtype=float)
    y_mm = np.asarray(hm["y_mm"], dtype=float)
    Z_mm = np.asarray(hm["Z_mm"], dtype=float)

    Z_det, _coef, _dmeta = exp07.robust_plane_fit_substrate_focused(
        Z_mm,
        x_mm,
        y_mm,
        y_excl=exp07.SUBSTRATE_EXCLUSION_Y_MM,
        stride_x=40,
        stride_y=2,
        max_iter=3,
    )
    fields, _fmeta = exp07.build_fields(Z_det, y_mm)
    cache = TrackDescriptorCache(
        track_id=int(track_id),
        x_mm=x_mm,
        y_mm=y_mm,
        fields=fields,
        x_min_mm=float(np.nanmin(x_mm)),
        x_max_mm=float(np.nanmax(x_mm)),
    )
    _TRACK_CACHE[track_id] = cache
    return cache


def load_regime_table() -> pd.DataFrame:
    """Load frozen Experiment 09 low-coherence regime metadata."""

    global _REGIME_TABLE
    if _REGIME_TABLE is None:
        _REGIME_TABLE = pd.read_csv(EXP09_DIR / "low_coherence_longitudinal_regimes.csv")
    return _REGIME_TABLE


def assign_regime_id(track_id: int, x_position_mm: float) -> str:
    """Assign frozen regime metadata without deriving new regimes."""

    if track_id == 10:
        regimes = load_regime_table()
        subset = regimes[regimes["track_id"].astype(int) == int(track_id)]
        for row in subset.itertuples(index=False):
            if float(row.x_min_mm) <= float(x_position_mm) <= float(row.x_max_mm):
                return str(row.regime_id)
        return "track_10_primary_coherent_regime"
    if track_id == 8:
        return "track_8_global_coherent_regime"
    if track_id == 14:
        return "track_14_global_coherent_regime"
    raise ValueError(f"Unsupported track_id={track_id}.")


def nearest_heightmap_column(cache: TrackDescriptorCache, x_position_mm: float) -> Tuple[int, float, float]:
    """Map a thermal anchor to the nearest measured profilometry column."""

    if float(x_position_mm) < cache.x_min_mm or float(x_position_mm) > cache.x_max_mm:
        return -1, float("nan"), float("nan")
    j = int(np.nanargmin(np.abs(cache.x_mm - float(x_position_mm))))
    x_used = float(cache.x_mm[j])
    return j, x_used, float(x_used - float(x_position_mm))


def invalid_out_of_heightmap_coverage_descriptor(track_id: int, x_position_mm: float) -> Dict[str, object]:
    """Return an explicit invalid descriptor when the anchor has no height-map support."""

    pc_scores = {f"pc{i}": float("nan") for i in range(1, N_RETAINED_PCA_COMPONENTS + 1)}
    return {
        **pc_scores,
        "amplitude_um": float("nan"),
        "signed_elevation_um": float("nan"),
        "eligible": False,
        "nonflat": False,
        "regime_id": assign_regime_id(track_id, float(x_position_mm)),
        "track_id": int(track_id),
        "x_position_mm": float(x_position_mm),
        "heightmap_x_mm": float("nan"),
        "heightmap_x_delta_mm": float("nan"),
        "heightmap_x_index": -1,
        "is_within_heightmap_x_coverage": False,
        "pca_ready": False,
        "finite_fraction": float("nan"),
        "central_corridor_finite_fraction": float("nan"),
        "substrate_side_finite_fraction": float("nan"),
        "baseline_support_count": float("nan"),
        "fallback_baseline_required": True,
        "is_within_boundary_exclusion": True,
        "shape_support_fraction_on_common_grid": float("nan"),
        "retained_pca_grid_finite_fraction": float("nan"),
        "normalization_status": "outside_heightmap_x_coverage",
        "shape_center_um_median": float("nan"),
        "shape_scale_um_mad": float("nan"),
    }


def evaluate_shape_profile(cache: TrackDescriptorCache, x_index: int) -> Tuple[np.ndarray, Dict[str, object]]:
    """Build the normalized profile and PCA-ready retained vector for one column."""

    pca = load_pca_model()
    y_full = np.asarray(pca["y_full_grid_mm"], dtype=float)
    retained_idx = np.asarray(pca["retained_full_grid_indices"], dtype=int)

    y_mm = cache.y_mm
    fields = cache.fields
    central_native = (y_mm >= CENTRAL_Y_MIN_MM) & (y_mm <= CENTRAL_Y_MAX_MM)
    z_um = np.asarray(fields["detrended_z_um"], dtype=float)
    finite = np.asarray(fields["finite_mask"], dtype=bool)
    valid_col = finite[:, x_index]
    central_valid = valid_col & central_native & np.isfinite(z_um[:, x_index])

    interp = exp09.interpolate_profile_without_gap_bridging(
        y_mm[central_native],
        z_um[central_native, x_index],
        central_valid[central_native],
        y_full,
    )
    norm, nmeta = exp09.normalize_shape(interp)
    normalization_support_ok = bool(float(nmeta["shape_support_fraction"]) >= MIN_NORMALIZATION_SUPPORT_FRACTION)
    nonflat = bool(nmeta["is_nonflat"] and normalization_support_ok)
    if not nonflat:
        norm = np.full_like(y_full, np.nan, dtype=float)

    retained = norm[retained_idx]
    pca_ready = bool(nonflat and np.isfinite(retained).all())
    return retained, {
        "shape_support_fraction_on_common_grid": float(nmeta["shape_support_fraction"]),
        "normalization_status": str(nmeta["normalization_status"]),
        "shape_center_um_median": float(nmeta["shape_center_um"]) if np.isfinite(nmeta["shape_center_um"]) else float("nan"),
        "shape_scale_um_mad": float(nmeta["shape_scale_um"]) if np.isfinite(nmeta["shape_scale_um"]) else float("nan"),
        "nonflat": bool(nonflat),
        "pca_ready": bool(pca_ready),
        "retained_pca_grid_finite_fraction": float(np.mean(np.isfinite(retained))),
    }


def score_pca(retained_profile: np.ndarray, pca_ready: bool) -> Dict[str, float]:
    """Project a normalized retained profile onto the frozen Experiment 11 PCA basis."""

    out = {f"pc{i}": float("nan") for i in range(1, N_RETAINED_PCA_COMPONENTS + 1)}
    if not pca_ready:
        return out
    pca = load_pca_model()
    centered = retained_profile - np.asarray(pca["mean_profile"], dtype=float)
    components = np.asarray(pca["components"], dtype=float)
    scores = centered @ components[:N_RETAINED_PCA_COMPONENTS, :].T
    for i, value in enumerate(scores, start=1):
        out[f"pc{i}"] = float(value)
    return out


def extract_geometry_descriptor(track_id: int, x_position_mm: float) -> Dict[str, object]:
    """Return the Experiment 12 geometry descriptor at one thermal anchor.

    The query x_position_mm is the canonical thermal anchor. Because the
    profilometer samples a native x grid, the descriptor is evaluated at the
    nearest measured height-map column and records the x offset explicitly.
    No values are filled or interpolated across invalid y-regions.
    """

    track_id = int(track_id)
    if track_id in SEALED_TRACKS:
        raise ValueError("Track 21 is sealed and must not be analyzed.")

    cache = load_track_cache(track_id)
    x_index, heightmap_x_mm, x_delta_mm = nearest_heightmap_column(cache, float(x_position_mm))
    if x_index < 0:
        return invalid_out_of_heightmap_coverage_descriptor(track_id, float(x_position_mm))
    fields = cache.fields
    y_mm = cache.y_mm

    finite = np.asarray(fields["finite_mask"], dtype=bool)
    signed = np.asarray(fields["signed_residual_um"], dtype=float)
    n_sub = np.asarray(fields["n_substrate_by_x"], dtype=float)
    central = (y_mm >= CENTRAL_Y_MIN_MM) & (y_mm <= CENTRAL_Y_MAX_MM)
    substrate = ~central

    valid_col = finite[:, x_index]
    central_valid = valid_col & central & np.isfinite(signed[:, x_index])
    substrate_valid = valid_col & substrate & np.isfinite(signed[:, x_index])
    central_values = signed[central_valid, x_index]

    total_finite_fraction = float(np.mean(valid_col))
    central_finite_fraction = float(np.sum(central_valid) / max(1, int(np.sum(central))))
    substrate_side_finite_fraction = float(np.sum(substrate_valid) / max(1, int(np.sum(substrate))))
    baseline_support_count = float(n_sub[x_index])
    fallback_baseline_required = bool(baseline_support_count < MIN_BASELINE_SUPPORT_COUNT)
    in_boundary_exclusion = bool(
        (heightmap_x_mm < cache.x_min_mm + BOUNDARY_EXCLUSION_MM)
        or (heightmap_x_mm > cache.x_max_mm - BOUNDARY_EXCLUSION_MM)
    )
    eligible = bool(
        (total_finite_fraction >= MIN_TOTAL_FINITE_FRACTION)
        and (central_finite_fraction >= MIN_CENTRAL_FINITE_FRACTION)
        and (baseline_support_count >= MIN_BASELINE_SUPPORT_COUNT)
        and (not in_boundary_exclusion)
    )

    amplitude_um = safe_iqr(central_values)
    signed_elevation_um = float(np.nanmedian(central_values)) if central_values.size else float("nan")

    retained_profile, shape_meta = evaluate_shape_profile(cache, x_index)
    pc_scores = score_pca(retained_profile, bool(shape_meta["pca_ready"]))

    descriptor: Dict[str, object] = {
        **pc_scores,
        "amplitude_um": float(amplitude_um),
        "signed_elevation_um": float(signed_elevation_um),
        "eligible": bool(eligible),
        "nonflat": bool(shape_meta["nonflat"]),
        "regime_id": assign_regime_id(track_id, float(x_position_mm)),
        "track_id": int(track_id),
        "x_position_mm": float(x_position_mm),
        "heightmap_x_mm": float(heightmap_x_mm),
        "heightmap_x_delta_mm": float(x_delta_mm),
        "heightmap_x_index": int(x_index),
        "is_within_heightmap_x_coverage": True,
        "pca_ready": bool(shape_meta["pca_ready"]),
        "finite_fraction": total_finite_fraction,
        "central_corridor_finite_fraction": central_finite_fraction,
        "substrate_side_finite_fraction": substrate_side_finite_fraction,
        "baseline_support_count": baseline_support_count,
        "fallback_baseline_required": fallback_baseline_required,
        "is_within_boundary_exclusion": in_boundary_exclusion,
        "shape_support_fraction_on_common_grid": float(shape_meta["shape_support_fraction_on_common_grid"]),
        "retained_pca_grid_finite_fraction": float(shape_meta["retained_pca_grid_finite_fraction"]),
        "normalization_status": str(shape_meta["normalization_status"]),
        "shape_center_um_median": float(shape_meta["shape_center_um_median"]),
        "shape_scale_um_mad": float(shape_meta["shape_scale_um_mad"]),
    }
    return descriptor


def output_columns() -> List[str]:
    pc_cols = [f"pc{i}" for i in range(1, N_RETAINED_PCA_COMPONENTS + 1)]
    return [
        "track_id",
        "frame_index",
        "x_position_mm",
        "heightmap_x_mm",
        "heightmap_x_delta_mm",
        "heightmap_x_index",
        "is_within_heightmap_x_coverage",
        *pc_cols,
        "amplitude_um",
        "signed_elevation_um",
        "eligible",
        "nonflat",
        "pca_ready",
        "regime_id",
        "finite_fraction",
        "central_corridor_finite_fraction",
        "substrate_side_finite_fraction",
        "baseline_support_count",
        "fallback_baseline_required",
        "is_within_boundary_exclusion",
        "shape_support_fraction_on_common_grid",
        "retained_pca_grid_finite_fraction",
        "normalization_status",
        "shape_center_um_median",
        "shape_scale_um_mad",
    ]


def write_track_descriptors(master: pd.DataFrame, out_dir: Path, track_id: int) -> pd.DataFrame:
    anchors = master[master["track_id"].astype(int) == int(track_id)].copy().reset_index(drop=True)
    rows: List[Dict[str, object]] = []
    for anchor in anchors.itertuples(index=False):
        desc = extract_geometry_descriptor(int(anchor.track_id), float(anchor.x_position_mm))
        desc["frame_index"] = int(anchor.frame_index) if hasattr(anchor, "frame_index") and pd.notna(anchor.frame_index) else np.nan
        rows.append(desc)
    df = pd.DataFrame(rows)
    cols = output_columns()
    df = df[cols]
    df.to_csv(out_dir / f"geometry_descriptors_track_{track_id}.csv", index=False)
    return df


def validation_summary(master: pd.DataFrame, outputs: Dict[int, pd.DataFrame]) -> Dict[str, object]:
    rows: Dict[str, object] = {}
    for track_id, df in outputs.items():
        expected = int(np.sum(master["track_id"].astype(int) == int(track_id)))
        pc_cols = [f"pc{i}" for i in range(1, N_RETAINED_PCA_COMPONENTS + 1)]
        rows[str(track_id)] = {
            "expected_anchor_rows": expected,
            "output_rows": int(len(df)),
            "row_count_matches": bool(len(df) == expected),
            "eligible_rows": int(df["eligible"].sum()),
            "nonflat_rows": int(df["nonflat"].sum()),
            "pca_ready_rows": int(df["pca_ready"].sum()),
            "rows_with_all_pc_scores": int(df[pc_cols].notna().all(axis=1).sum()),
            "rows_with_nan_pc_scores": int(df[pc_cols].isna().any(axis=1).sum()),
            "outside_heightmap_x_coverage_rows": int((~df["is_within_heightmap_x_coverage"]).sum()),
            "fallback_baseline_rows": int(df["fallback_baseline_required"].sum()),
            "boundary_exclusion_rows": int(df["is_within_boundary_exclusion"].sum()),
            "max_abs_heightmap_x_delta_mm": float(np.nanmax(np.abs(df["heightmap_x_delta_mm"].to_numpy(dtype=float))))
            if np.any(np.isfinite(df["heightmap_x_delta_mm"].to_numpy(dtype=float)))
            else float("nan"),
            "regime_counts": df["regime_id"].value_counts(dropna=False).to_dict(),
        }
    return rows


def main() -> int:
    run_tag = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_dir = REPO_ROOT / "processed_data" / "run_outputs" / f"12_geometry_descriptor_implementation_{run_tag}"
    table_dir = out_dir / "tables"
    table_dir.mkdir(parents=True, exist_ok=True)

    master = pd.read_csv(PHASE1_MASTER_PATH)
    observed_tracks = sorted(int(v) for v in master["track_id"].dropna().unique())
    if 21 in observed_tracks:
        # Track 21 may exist in the master table, but remains sealed and is ignored.
        pass

    outputs: Dict[int, pd.DataFrame] = {}
    for track_id in TRACK_IDS:
        outputs[track_id] = write_track_descriptors(master, table_dir, track_id)

    validation = validation_summary(master, outputs)
    metadata = {
        "experiment": "12_geometry_descriptor_implementation",
        "out_dir": str(out_dir),
        "tracks_processed": TRACK_IDS,
        "sealed_tracks": sorted(SEALED_TRACKS),
        "phase1_master": str(PHASE1_MASTER_PATH),
        "anchor_grid": "track_id and x_position_mm rows from processed_data/phase1_unified_master.csv; no representative, dense native, or uniform 1 mm grid evaluated.",
        "preprocessing_reuse": {
            "experiment07_script": str(EXP07_PATH),
            "experiment09_script": str(EXP09_PATH),
            "heightmap_loader": "src/nsf_fmrg_data.py::load_wyko_asc",
            "detrending": "Experiment 07 substrate-focused plane detrending with central exclusion band.",
            "baseline_fields": "Experiment 07 per-column substrate baseline/spread fields.",
            "normalization": "Experiment 09 central-corridor interpolation-without-gap-bridging and median/MAD normalization.",
        },
        "pca_reuse": {
            "source": str(EXP11_DIR / "pca_model_arrays.npz"),
            "n_retained_descriptor_components": int(N_RETAINED_PCA_COMPONENTS),
            "pca_component_fields": [f"pc{i}" for i in range(1, N_RETAINED_PCA_COMPONENTS + 1)],
        },
        "shared_configuration": {
            "central_corridor_y_mm": [CENTRAL_Y_MIN_MM, CENTRAL_Y_MAX_MM],
            "boundary_exclusion_mm": BOUNDARY_EXCLUSION_MM,
            "min_total_finite_fraction": MIN_TOTAL_FINITE_FRACTION,
            "min_central_finite_fraction": MIN_CENTRAL_FINITE_FRACTION,
            "min_baseline_support_count": MIN_BASELINE_SUPPORT_COUNT,
            "min_normalization_support_fraction": MIN_NORMALIZATION_SUPPORT_FRACTION,
        },
        "descriptor_schema": output_columns(),
        "implementation_assumptions": [
            "Thermal x_position_mm values are the canonical query anchors; each anchor is mapped to the nearest measured profilometry x-column, and the offset is recorded in heightmap_x_delta_mm.",
            "Anchors outside measured height-map x coverage are retained as rows with explicit invalid status and NaN descriptor values, not clamped to the nearest measured column.",
            "amplitude_um is the central-corridor signed-residual IQR, matching Experiment 10's local relief interpretation.",
            "signed_elevation_um is the central-corridor median signed residual relative to the Experiment 07 substrate baseline.",
            "regime_id reuses Experiment 09 Track 10 low-coherence intervals; Tracks 8 and 14 receive global coherent-regime labels.",
            "PCA scores are emitted only when the normalized retained PCA y-grid is complete; otherwise pc fields remain NaN and pca_ready is False.",
        ],
        "validation_summary": validation,
        "outputs": {
            "tables": sorted([p.name for p in table_dir.iterdir()] + ["run_metadata.json"]),
        },
    }
    (table_dir / "run_metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    print(f"Wrote Experiment 12 outputs to: {out_dir}")
    for track_id, stats in validation.items():
        print(
            f"Track {track_id}: rows {stats['output_rows']}/{stats['expected_anchor_rows']}, "
            f"eligible={stats['eligible_rows']}, nonflat={stats['nonflat_rows']}, "
            f"pca_ready={stats['pca_ready_rows']}, max|dx|={stats['max_abs_heightmap_x_delta_mm']:.6f} mm"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
